### ISSUE TITLE
Gamesession result/completed page에서의 Report 기능 강화

### ISSUE THREAD

**Issue by iNCurrO** [glossm/web#11]
점수뿐만 아니라, 제출한 답안을 비롯하여 여러 정보를 보여줌

**Comment by gunwooterry** [comment]
지금은 제출한 답안, 점수, 다른 사람들이 입력한 상위 답안, 이렇게 총 3종류의 정보를 보여줍니다.
추가적으로 보여줄 만한 정보가 어떤 게 있을까요?

**Comment by iNCurrO** [comment]
당장 떠오르는 것은
문제별 -> 평균 답안(? 혹은 답이 알려져 있는 문제라면 정답), 평균 유사도,
최종 -> 전체적인 답안 요약 정리,  유사한 토픽/난이도 set
이 있습니다.

향후 계속해서 개선되어야할 페이지라고 생각됩니다.
물론 기능지원을 위해 API 추가가 필요할태구요...

**Comment by mnkykm** [comment]
#25 로 이전하겠습니다.
