### ISSUE TITLE
Meanings layout in AnswerSession

### ISSUE THREAD

**Issue by gunwooterry** [glossm/web#14]
`AnswerSession`에서 현재 `Record`의 한국어, 영어, 러시아어, 중국어, 몽골어 의미 표시

**Comment by minkyuxyz** [comment]
이슈는 그대로 두십시오. 더 나은 디스플레이 방식을 구현하면 그 때 닫읍시다.

**Comment by mnkykm** [comment]
#24 로 이전하겠습니다.
